datagrid:
    adit-simple-grid:
        source:
            type: orm
            query:
                select:
                    - adit_project.id
                    - adit_project.naziv
                from:
                    - { table: %adit_simple.project.entity.class%, alias: adit_project }
        columns:
            id:
                label: adit_simple.project.id.label
            naziv:
                label: adit_simple.project.naziv.label
        properties:
            id: ~
            update_link:
                type:       url
                route:      adit_simple_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      adit_simple_delete
                params:     [ id ]
        actions:
            update:
                type:          navigate
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          navigate
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link