parameters:
    adit_simple.form.type.class:         Adit\Bundle\ProjectBundle\Form\Type\ProjectType
    adit_simple.form.handler.class:      Adit\Bundle\ProjectBundle\Form\Handler\ProjectHandler

services:
    adit_simple.form.type:
        class: %adit_simple.form.type.class%
        tags:
            - { name: form.type, alias: adit_project_form }

    adit_simple.form.handler:
        class: %adit_simple.form.handler.class%
        scope: request
        arguments:
            - "adit_project_form"
            - "adit_project_form"
            - @request
            - @doctrine.orm.entity_manager
            - @oro_entity.routing_helper
            - @form.factory