datagrid:
    adit-projects-grid:
        source:
            type: orm
            query:
                select: [ status.id, status.status ]
                from:
                    - { table: projectStatus, alias:status }

        columns:
            id:
                label: 'Id'
            status:
                label: 'Status'