oro_menu_config:
    items:
        projekti_tab:
            label: Projekti
            uri:   '#'
            extras:
                position: 300
        projekti_tab_link:
            label: Lista projekata
            route: oro_entity_index
            routeParameters:
                entityName: Extend_Entity_Projekt
    tree:
        application_menu:
            children:
                projekti_tab:
                    children:
                        projekti_tab_link: ~
 
oro_titles:
    projekti_link: Prikazi projekte