oro_menu_config:
    items:
        projekti_tab:
            label: Projekti
            uri:   '#'
            extras:
                position: 300
        projekt_statusi_tab_link:
            label: Lista statusa
            route: adit_statusi_link
        projekt_tipovi_tab_link:
            label: Lista tipova
            route: adit_tipovi_link
    tree:
        application_menu:
            children:
                projekti_tab:
                    children:
                        projekt_statusi_tab_link: ~
                        projekt_tipovi_tab_link: ~
 
oro_titles:
    projekti_link: Prikazi projekte